name: test-action

on:
  push:
    branches: [ "feature/20-add-ci-yaml" ]
    
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      AWS_CLI_VERSION: "2.10.0"
    name: AWS CLI 설치 (v${{ env.AWS_CLI_VERSION }})
    steps:
      - name: AWS CLI 설치 (v${{ env.AWS_CLI_VERSION }})
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: ${{ env.AWS_CLI_VERSION }}
      - run: aws --version
        shell: bash